apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- my-express-app-deployment.yaml
- my-express-app-service.yaml
namespace: my-express-app
images:
- name: ghcr.io/enfojt/nodejs-example
  newName: ghcr.io/enfojt/nodejs-example
  newTag: 3a7d8a8834b6691dac933a9a8aa66c4e640ef6e0
