apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- my-express-app-deployment.yaml
- my-express-app-service.yaml
namespace: my-express-app
images:
- name: ghcr.io/enfojt/nodejs-example
  newName: ghcr.io/enfojt/nodejs-example
  newTag: bd973e18524102abc3e89c5387756e79176f6e43
